version: 2
updates:
  # Check if a new OCI image is available
  - package-ecosystem: "docker"
    schedule:
      interval: "daily"
    directory: "/"
    open-pull-requests-limit: 5 # Limits the number of open PRsd